default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :tests do
    scan(scheme: "KoeNaWin")
  end

  desc "Lint code using SwiftFormat"
  lane :lint do
    sh "swiftformat --swiftversion 5.10 ."
  end

  desc "Sync development certificates and profiles"
  lane :sync_development_signing do
    match(type: "development", readonly: true)
  end

  desc "Build and upload to TestFlight for UAT"
  lane :build_and_upload_to_testflight do
    _app_store_authenticate
    match(type: "appstore", readonly: is_ci)
    _ensure_build_number
    build_app(scheme: "KoeNaWin")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to the App Store"
  lane :deploy_to_app_store do
    _app_store_authenticate
    match(type: "appstore", readonly: is_ci)
    _ensure_build_number
    build_app(scheme: "KoeNaWin")
    upload_to_app_store(
      force: true, # Set to true to skip asking for confirmation
      submit_for_review: true,
      automatic_release: false # Set to true to automatically release the app after approval
    )
  end

  # Private lane to handle build number increment
  private_lane :_ensure_build_number do
    # Get the latest build number from TestFlight
    latest_build = latest_testflight_build_number(app_identifier: "com.nanda.KoeNaWin")
    
    # Set the new build number
    new_build_number = latest_build + 1
    increment_build_number(build_number: new_build_number)
    
    UI.message("Set build number to #{new_build_number}")
  end

  # Private lane for App Store Connect API Key authentication
  private_lane :_app_store_authenticate do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_KEY_CONTENT"]
    )
  end
end
